In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [4]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [5]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [7]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [12]:
df = pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])

In [13]:
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [14]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [15]:
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension radius error texture error perimeter error  \
0                0.07871       1.0950        0.9053           8.589   
1                0.05667       0.5435        0.7339           3.398   
2                0.05999       0.7456        0.7869           4.585   
3                0.09744       0.4956        1.1560           3.445   
4                0.05883       0.7572        0.7813           5.438   

  area error smoothness error compactness error concavity error  \
0     153.40         0.006399           0.04904         0.05373   
1      74.08         0.005225           0.01308         0.01860   
2      94.03         0.006150           0.04006         0.03832   
3      27.23         0.009110           0.07458         0.05661   
4      94.44         0.011490           0.02461         0.05688   

  concave points error symmetry error fractal dimension error worst radius  \
0              0.01587        0.03003                0.006193        25.38   
1              0.01340        0.01389                0.003532        24.99   
2              0.02058        0.02250                0.004571        23.57   
3              0.01867        0.05963                0.009208        14.91   
4              0.01885        0.01756                0.005115        22.54   

  worst texture worst perimeter worst area worst smoothness worst compactness  \
0         17.33          184.60     2019.0           0.1622            0.6656   
1         23.41          158.80     1956.0           0.1238            0.1866   
2         25.53          152.50     1709.0           0.1444            0.4245   
3         26.50           98.87      567.7           0.2098            0.8663   
4         16.67          152.20     1575.0           0.1374            0.2050   

  worst concavity worst concave points worst symmetry worst fractal dimension  \
0          0.7119               0.2654         0.4601                 0.11890   
1          0.2416               0.1860         0.2750                 0.08902   
2          0.4504               0.2430         0.3613                 0.08758   
3          0.6869               0.2575         0.6638                 0.17300   
4          0.4000               0.1625         0.2364                 0.07678   

  target  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

In [16]:
df.shape

(569, 31)

In [17]:
#split data
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [18]:
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: (target,), dtype: float64

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=40)

In [33]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [34]:
#model building
from sklearn.tree import DecisionTreeClassifier
dc = DecisionTreeClassifier(criterion='gini')
dc.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


DecisionTreeClassifier()

In [35]:
dc.score(x_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9473684210526315

In [36]:
from sklearn.tree import DecisionTreeClassifier
dc_ent = DecisionTreeClassifier(criterion='entropy')
dc_ent.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


DecisionTreeClassifier(criterion='entropy')

In [37]:
dc_ent.score(x_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9385964912280702

Feature Scaling

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [45]:
dc_ss = DecisionTreeClassifier(criterion='gini')
dc_ss.fit(x_train,y_train)

DecisionTreeClassifier()

In [46]:
dc_ss.score(x_test,y_test)

0.9473684210526315

In [47]:
patient = x_test[0]

array([-0.09228615, -1.24452711, -0.15568769, -0.19520877, -0.36326958,
       -0.8014783 , -0.99441792, -0.76192463, -0.79122189, -0.58798595,
       -0.59948021, -0.92932543, -0.60584511, -0.44061404, -0.80665792,
       -0.9331956 , -1.05115282, -0.74259795,  0.21327428, -0.73813365,
       -0.32789702, -1.31405154, -0.39023394, -0.38365288, -0.68807598,
       -0.8837119 , -1.1074687 , -0.82575522, -0.11013446, -0.83020561])

In [51]:
patient = np.array([patient])

In [52]:
patient

array([[-0.09228615, -1.24452711, -0.15568769, -0.19520877, -0.36326958,
        -0.8014783 , -0.99441792, -0.76192463, -0.79122189, -0.58798595,
        -0.59948021, -0.92932543, -0.60584511, -0.44061404, -0.80665792,
        -0.9331956 , -1.05115282, -0.74259795,  0.21327428, -0.73813365,
        -0.32789702, -1.31405154, -0.39023394, -0.38365288, -0.68807598,
        -0.8837119 , -1.1074687 , -0.82575522, -0.11013446, -0.83020561]])

In [53]:
dc_ss.predict(patient)

array([1.])

In [55]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')